-- MySQL Script generated by MySQL Workbench
-- Wed Nov 22 14:10:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


DROP TABLE IF EXISTS `frieseck_hodnoceni` ;
DROP TABLE IF EXISTS `frieseck_prava` ;
DROP TABLE IF EXISTS `frieseck_uzivatele` ;
DROP TABLE IF EXISTS `frieseck_prispevky` ;

-- -----------------------------------------------------
-- Table `mydb`.`frieseck_prava`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frieseck_prava` (
  `id_prava` INT NOT NULL,
  `nazev` VARCHAR(20) NOT NULL,
  `vaha` INT(2) NOT NULL,
  PRIMARY KEY (`id_prava`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frieseck_uzivatele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frieseck_uzivatele` (
  `id_uzivatel` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(60) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `heslo` VARCHAR(40) NOT NULL,
  `email` VARCHAR(35) NOT NULL,
  `ban` INT NOT NULL DEFAULT 1, -- 1 nema ban - 2 ma bam
  `id_prava` INT NOT NULL DEFAULT 3,
  PRIMARY KEY (`id_uzivatel`),
  INDEX `fk_frieseck_uzivatele_frieseck_prava_idx` (`id_prava` ASC),
  CONSTRAINT `fk_frieseck_uzivatele_frieseck_prava`
    FOREIGN KEY (`id_prava`)
    REFERENCES `frieseck_prava` (`id_prava`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frieseck_prispevky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frieseck_prispevky` (
  `id_prispevky` INT NOT NULL AUTO_INCREMENT,
  `titulek` VARCHAR(150) NOT NULL,
  `text` MEDIUMBLOB NOT NULL,
  `datum` DATE NOT NULL,
  `publikovan` INT DEFAULT 1, -- 1 fronta - 2 ano - 3 ne
  `id_uzivatel` INT NOT NULL,
  PRIMARY KEY (`id_prispevky`, `titulek`),
  INDEX `fk_frieseck_prispevky_frieseck_uzivatele1_idx` (`id_uzivatel` ASC),
  CONSTRAINT `fk_frieseck_prispevky_frieseck_uzivatele1`
    FOREIGN KEY (`id_uzivatel`)
    REFERENCES `frieseck_uzivatele` (`id_uzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frieseck_hodnoceni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frieseck_hodnoceni` (
  `id_hodnoceni` INT NOT NULL AUTO_INCREMENT,
  `text` BLOB,
  `datum` DATE,
  `stav` INT DEFAULT 0,
  `id_uzivatel` INT NOT NULL,
  `id_prispevky` INT NOT NULL,
  PRIMARY KEY (`id_hodnoceni`, `id_uzivatel`, `id_prispevky`),
  INDEX `fk_frieseck_hodnoceni_frieseck_uzivatele1_idx` (`id_uzivatel` ASC),
  INDEX `fk_frieseck_hodnoceni_frieseck_prispevky1_idx` (`id_prispevky` ASC),
  CONSTRAINT `fk_frieseck_hodnoceni_frieseck_uzivatele1`
    FOREIGN KEY (`id_uzivatel`)
    REFERENCES `frieseck_uzivatele` (`id_uzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frieseck_hodnoceni_frieseck_prispevky1`
    FOREIGN KEY (`id_prispevky`)
    REFERENCES `frieseck_prispevky` (`id_prispevky`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
